### ISSUE TITLE
tsc errors: `implicitly has an 'any' type.`, and others

### ISSUE THREAD

**Issue by erikschul** [withastro/starlight#1607] opened 2024-03-06 15:11 UTC
### What version of `starlight` are you using?

head

### What version of `astro` are you using?

N/A

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

None

### Describe the Bug

I created a pnpm workspace consisting of:
- the `packages/starlight` folder, with the `tsconfig.json` from the root
- the starlight starter project
and updated the package.json to link it locally.

But when I open the Hero component, I get these errors.

Is it possible that you are not compiling the project with tsc and therefore don't see these errors?
Or did I misconfigure something?
Is it best practice to use `any` type in Astro (because strong typing is too hard?), or is this a mistake?

```
[{
    "resource": "/components/Hero.astro",
    "owner": "_generated_diagnostic_collection_name_#0",
    "code": "7031",
    "severity": 8,
    "message": "Binding element 'text' implicitly has an 'any' type.",
    "source": "ts",
    "startLineNumber": 53,
    "startColumn": 22,
    "endLineNumber": 53,
    "endColumn": 26
},{
    "resource": "/components/Hero.astro",
    "owner": "_generated_diagnostic_collection_name_#0",
    "code": "2322",
    "severity": 8,
    "message": "Type '{ \"set:html\": any; }' is not assignable to type 'IntrinsicAttributes & Props'.\n  Type '{ \"set:html\": any; }' is missing the following properties from type 'Props': variant, link",
    "source": "ts",
    "startLineNumber": 54,
    "startColumn": 8,
    "endLineNumber": 54,
    "endColumn": 20
}]
```

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2024-05-20 20:45
Hi @erikschul, thanks for your patience on this one! I just took a quick look, but I’m not able to reproduce it. Going to assume it was maybe fixed in the meantime. Feel free to provide more information if this is still causing issues.

**Closed by delucis** 2024-05-20 20:45 UTC
