### ISSUE TITLE
Tailwind Plugin breaks existing page design

### ISSUE THREAD

**Issue by spaceemotion** [withastro/starlight#746] opened 2023-09-22 21:11 UTC
### What version of `starlight` are you using?

0.10.1

### What version of `astro` are you using?

3.1.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I just installed Starlight into an existing astro project, in wich the documentation should live under `/docs`. As I already use tailwind, I only added the plugin and imported the `main.css` into the starlight config.

However, adding the tailwind plugin overwrites the base CSS reset Tailwind uses.

I already tried splitting up my tailwind config, one for the website and one for the docs and use `@config` at the top of the file.
For some reason astro still picks the `docs.css` over `main.css`. 

Right now, all my buttons and links look like this (font fell back to Times New Roman):
![image](https://github.com/withastro/starlight/assets/429147/2e1b2c09-a389-493d-8c7b-fcff6b22241a)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2023-09-28 08:41
Thanks for the issue @spaceemotion!

Could you share a list of the styles that you lost?

It would also be helpful to see some code/a reproduction as there are a lot of moving parts here (existing site routes, Tailwind config, CSS files, Starlight config, etc), so it's hard to know what the issue is without a bit more detail.

**Comment by Uzaaft** [comment] 2023-09-29 18:43
Styles breaks for me by just setting up a starlight repo with the template, and running: `npx astro add tailwindcss`.
After adding tailwindcss:
<img width="1642" alt="image" src="https://github.com/withastro/starlight/assets/48220549/b7d56d0e-3e08-41f2-94d9-24ede2efbeca">
Before:

<img width="1634" alt="image" src="https://github.com/withastro/starlight/assets/48220549/5aa09ac3-476c-4a91-813c-16d8daf11e36">

**Comment by Boston343** [comment] 2023-09-30 03:41
I am trying to get starlight running on an existing site as well. I also noticed that the tailwind integration broke things. The solution I found was to disable default styles in Tailwind. So in the astro config file use this:

```js
integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
    starlight({
      title: "My Docs",
    }),
  ],
```

**Comment by delucis** [comment] 2023-10-24 20:57
Thanks everyone. Reading this it sounds like there are two scenarios:

1. Tailwind was added, but without following our [Starlight + Tailwind guide](https://starlight.astro.build/guides/css-and-tailwind/#tailwind-css), meaning some Tailwind styles that conflict with Starlight being applied. In this case, I’d recommend reading through that guide as it explains how to get Tailwind working inside your Starlight pages.

2. Tailwind was added, but was only actually needed in some non-Starlight pages. The fix here was using `applyBaseStyles: false` and importing a Tailwind `base.css` only in the pages that needed it as per [the Astro Tailwind docs](https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles).

We could potentially add a note about that second case to the Starlight docs, but for now I feel like there isn’t a bug described here for us to fix, so going to close this as resolved.

**Closed by delucis** 2023-10-24 20:57 UTC

**Comment by spaceemotion** [comment] 2023-10-24 20:59
@delucis let me try if i can build up an example this week, because this hasn't been my experience. i did follow the guide and it definitely didn't work as expected. maybe it has been fixed in the meanwhile without me noticing though! i still have that cobbled-together setup that somewhat works.

**Comment by delucis** [comment] 2023-10-24 21:02
@spaceemotion Thanks! Yeah, a reproduction would be super helpful in understanding what’s up.
