### ISSUE TITLE
Failing to import night-owl-dark.jsonc?raw

### ISSUE THREAD

**Issue by ronildo** [withastro/starlight#1543] opened 2024-02-21 13:50 UTC
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

4.3.7

### What package manager are you using?

bun

### What operating system are you using?

Linux

### What browser are you using?

Any

### Describe the Bug

When I run the project in dev, I'm getting this error from the image.
It doesn't break anything, just wondering if I should worry about it.

![Screenshot 2024-02-21 at 8 47 40 AM](https://github.com/withastro/starlight/assets/622159/2015be53-1e40-4417-8273-52ccaf28788c)

### Link to Minimal Reproducible Example

*

### Participation

- [ ] I am willing to submit a pull request for this issue.

Worth mentioning I'm using SSR, here is my astro config:
```javascript
import nodejs from '@astrojs/node'
import react from '@astrojs/react'
import starlight from '@astrojs/starlight'
import tailwind from '@astrojs/tailwind'
import { defineConfig, passthroughImageService } from 'astro/config'

export default defineConfig({
	output: 'server',
	adapter: nodejs({ mode: 'standalone' }),
	image: {
		service: passthroughImageService()
	},
	integrations: [
		react(),
		starlight({
			title: 'Trillian Docs'
		}),
		tailwind({
			applyBaseStyles: false
		})
	]
})

```

**Comment by delucis** [comment] 2024-02-21 15:43
Hi @ronildo! Could you please share a minimal reproduction we can debug?

The best way to do this is to create a new StackBlitz and modify it so it exhibits the error you’re experiencing (e.g. adding SSR etc.)

Here’s a quick link to create a Starlight starter project on StackBlitz: https://astro.new/starlight-basics

**Comment by hippotastic** [comment] 2024-02-21 15:47
I don't think that this actually is an issue we need to worry about. This is just a debug message coming from Astro, and afterwards Astro loads the same config with Vite, which apparently succeeds, otherwise your page wouldn't be working. :)

**Comment by delucis** [comment] 2024-02-22 08:59
Ah, thanks @hippotastic! Ok, then closing as not a bug but something specific to how Bun logs warnings from Astro/Vite.

**Closed by delucis** 2024-02-22 08:59 UTC
Labels: needs-reproduction

**Comment by aleclarson** [comment] 2024-04-09 21:39
I'm not using Bun and this error is appearing still.

```
✘ [ERROR] No loader is configured for ".jsonc" files: node_modules/.pnpm/@astrojs+starlight@0.21.5_astro@4.5.17/node_modules/@astrojs/starlight/integrations/expressive-code/themes/night-owl-light.jsonc?raw

    node_modules/.pnpm/@astrojs+starlight@0.21.5_astro@4.5.17/node_modules/@astrojs/starlight/integrations/expressive-code/theming.ts:3:26:
      3 │ import nightOwlLight from './themes/night-owl-light.jsonc?raw';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".jsonc" files: node_modules/.pnpm/@astrojs+starlight@0.21.5_astro@4.5.17/node_modules/@astrojs/starlight/integrations/expressive-code/themes/night-owl-dark.jsonc?raw

    node_modules/.pnpm/@astrojs+starlight@0.21.5_astro@4.5.17/node_modules/@astrojs/starlight/integrations/expressive-code/theming.ts:2:25:
      2 │ import nightOwlDark from './themes/night-owl-dark.jsonc?raw';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- `astro` v4.5.17
- `@astrojs/starlight` v0.21.5

**Comment by hippotastic** [comment] 2024-04-10 03:32
Does the site still work, so just an error logged to the console? Have you enabled any flags regarding verbose logging?

**Comment by aleclarson** [comment] 2024-04-10 03:56
Hi @hippotastic, the site does not work, since the client-side error page is shown (at least during development, I haven't tested `astro build` yet).

Here are the verbose logs: https://gist.github.com/aleclarson/9f5f474245720ec9fa452d89d1c5a34b

**Comment by hippotastic** [comment] 2024-04-10 04:04
It seems that you are importing server-side code into a frontend file.

Can you share a link to your repo?

**Comment by aleclarson** [comment] 2024-04-10 17:15
I'm trying to set up the following file structure:
```
docs/
├─ content/
│  ├─ .git/
│  ├─ reference/
├─ www/
│  ├─ .git/
│  ├─ astro.config.mjs
```

…with `srcDir` set to `../`.

I assume this setup is not supported, so I'll try having content within `www` instead. This should be fine, since the main goal is to give the content its own git branch, away from the Astro stuff.

**Comment by ronildo** [comment] 2024-04-10 17:40
> I'm trying to set up the following file structure:
> 
> ```
> docs/
> ├─ content/
> │  ├─ .git/
> │  ├─ reference/
> ├─ www/
> │  ├─ .git/
> │  ├─ astro.config.mjs
> ```
> 
> …with `srcDir` set to `../`.
> 
> I assume this setup is not supported, so I'll try having content within `www` instead. This should be fine, since the main goal is to give the content its own git branch, away from the Astro stuff.

Are you using workspaces? This might be the issue, I have been having lots of issues like this... but I'm still able to build/server the app.


![Screenshot 2024-04-10 at 1 39 56 PM](https://github.com/withastro/starlight/assets/622159/5a083baf-0d19-46d9-9ba7-4b3fce045a54)

**Comment by hippotastic** [comment] 2024-04-10 17:46
> …with `srcDir` set to `../`.

Ahh, I think this is the issue then! If your content is outside of the project root, this might lead to it not being processed by Vite, and therefore the special import suffixes powered by Vite (like `?raw`) don't work.
