### ISSUE TITLE
Embed Microsoft Video Not Working on Safari

### ISSUE THREAD

**Issue by wyaaung** [withastro/starlight#1497] opened 2024-02-15 12:07 UTC
### What version of `starlight` are you using?

0.17.3

### What version of `astro` are you using?

4.3.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

![Screenshot 2024-02-15 at 12 03 59](https://github.com/withastro/starlight/assets/73614550/2e94b907-6fc5-4e79-8d40-52f5c6ffc9f4)

I am trying to put an embedded video into the markdown file there. It asked me to log in to my Microsoft Active Directory account. But it didn't change to the video.

Expected Behavior

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2024-02-15 15:46
Thanks for your report.

I tried to repro the issue using a video hsoted on OneDrive but creating an embed for it automatically make it public:

> Note: Anyone who visits the blog or webpage with this embedded file will be able to view it without signing in.

To help investigate the issue, I have a few questions:

- How do you embed the video? Could you please share the code? (you can obfuscate the URL)
- Does this work in another browser?
- Does this work in Safari outside of Starlight?

**Comment by wyaaung** [comment] 2024-02-16 10:04
> * Does this work in another browser?

Here is the Markdown that I used.

```
---
title: New Starters (Core Tooling Specific)
description: New Starters (Core Tooling)
# template: 'splash'
---

This is an example page for new starters.

![Screenshot of Knowledge Sharing Confluence](../../assets/sample-one.png "Screenshot of Knowledge Sharing Confluence")

<iframe src="https://hutgroupnorthwich.sharepoint.com/sites/Teepee-Public/_layouts/15/embed.aspx?UniqueId=494de5da-7719-40e1-81a9-e3ae31a7247e&embed=%7B%22ust%22%3Atrue%2C%22hv%22%3A%22CopyEmbedCode%22%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create" width="1080" height="720" frameborder="0" scrolling="no" allowfullscreen title="Widgets Library — Introduction Video-20240212_121102-Meeting Recording.mp4"></iframe>

```

It works in other browsers, except Safari.

**Comment by delucis** [comment] 2024-02-16 10:31
Hi @wyaaung, thanks for taking the time to make an issue!

I don’t think this problem is caused by Starlight. The `<iframe>` in this case is rendered verbatim and if it shows differences between browsers that is likely due to the browser or Microsoft’s embed code — unfortunately both things we do not control.

Happy to keep chatting here if you have further questions, but will close this issue as something unrelated to Starlight.

If you can show us that the embed works in another non-Starlight page, and that it’s only on the Starlight page that it has problems, then we can take a closer look.

**Closed by delucis** 2024-02-16 10:31 UTC
Labels: needs-reproduction
