### ISSUE TITLE
Allow for setting a target to the anchor tag in the sidebar (SidebarLinkItem)

### ISSUE THREAD

**Issue by khendrikse** [withastro/starlight#497] opened 2023-08-11 12:26 UTC
### What version of `starlight` are you using?

0.6.0

### What is your idea?

For a project I'm working on I'd love to be able to set some of the link items in the sidebar to open in a new window/tab. For this I'd love it if we could support setting a target. Setting the `rel="noopener noreferrer"` if the target is `_blank`.

### Why is this feature necessary?

Sometimes you might want to open external sites but keep the current site open, especially for software platforms this could be relevant :) 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2023-08-12 17:13
Thank you for the issue and the accompanying PR @khendrikse!

I think we might want to consider this a duplicate of #395, which proposed allowing adding any arbitrary attribute to the sidebar items (not just `target`). There’s also an open issue for adding badges to sidebar items (#478), so seems we have a few different examples where people want control over the sidebar items.

Would you be OK if we use #395 as the main discussion thread for this topic?

**Comment by khendrikse** [comment] 2023-08-15 07:56
@delucis 100%! That makes sense :)

**Comment by delucis** [comment] 2023-08-15 08:22
OK great! I added a comment in #395 about link targets and we can close this thread as a duplicate of that. Thanks again for pointing out this use case.

**Closed by delucis** 2023-08-15 08:22 UTC
