### ISSUE TITLE
left TOC scrollbar position lost on transition

### ISSUE THREAD

**Issue by pelikhan** [withastro/starlight#1859] opened 2024-05-13 15:27 UTC
### What version of `starlight` are you using?

0.22.2

### What version of `astro` are you using?

4.8.2

### What package manager are you using?

yarn

### What operating system are you using?

windows,linux,macos

### What browser are you using?

edge

### Describe the Bug

It would be great of if the left TOC could scroll the selected page item into view. Currently, it resets the scroll position so, if the TOC is long enough, the select page item is hidden after a transition.

### Link to Minimal Reproducible Example

https://microsoft.github.io/genaiscript/reference/cli/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2024-05-13 16:25
Thanks for your feedback :raised_hands:

This is indeed something that has been heavily discussed in this [thread](https://github.com/withastro/starlight/discussions/971), which also contains a few existing solutions/workarounds for it. The feature is also being worked in this [PR](https://github.com/withastro/starlight/pull/1121) at the moment.

I'm going to close this issue as a duplicate of the existing discussion, but feel free to comment there if you have any questions or suggestions.

**Closed by HiDeoo** 2024-05-13 16:25 UTC

**Comment by pelikhan** [comment] 2024-05-13 16:46
Thank you for the quick answer!
