### ISSUE TITLE
Content from MDX component isn't indexed

### ISSUE THREAD

**Issue by VojtaStruhar** [withastro/starlight#561] opened 2023-08-24 11:55 UTC
### What version of `starlight` are you using?

0.7.3

### What version of `astro` are you using?

2.10.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

Content in a `.mdx` file that comes from imported component (`.astro`) doesn't get indexed.

- ~~After build, fulltext search doesn't work on it~~ _sorry_
- Headings don't appear in left sidebar (table of contents)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xs3vfn?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2023-08-24 14:42
This may be related to https://github.com/withastro/astro/issues/5084 and also this closed PR https://github.com/withastro/astro/pull/6922.

Basically, non-markdown headings do not show up in the TOC and this is used to exclude headings from the ToC.

It looks like Docusaurus also uses [the same pattern](https://docusaurus.io/docs/markdown-features/toc#customizing-table-of-contents-generation) and they have a [discussion](https://github.com/facebook/docusaurus/issues/6201) to gather feedback on this behavior.

If this is a behavior that is preserved, then I think this should at least be documented.

**Comment by delucis** [comment] 2023-08-28 10:53
Thanks for the issue and the clear reproduction @VojtaStruhar!

I’ve hit similar cases before and usually what I do is to provide headings I want to display in the sidebar something like this:

```mdx
---
title: MDX page
---

<Component>

## Heading for component

</Component>
```

```astro
---
// Component.astro
---

<div>
  <slot />
  <p>More component content</p>
</div>
```

This keeps the heading as Markdown/MDX content so Astro can collect it for the table of contents.

As @HiDeoo mentioned, this is a behaviour in Astro’s collection of page headings in Markdown and MDX and not something we can control in Starlight, so going to close this as beyond Starlight’s control. I still really appreciate the issue — hopefully this workaround helps.

If you have ideas for how to improve Astro’s handling of headings in cases like this, a discussion in the Astro roadmap repo would be a good place to start: https://github.com/withastro/roadmap/discussions/

**Closed by delucis** 2023-08-28 10:53 UTC

**Comment by VojtaStruhar** [comment] 2023-08-28 19:51
Thank you for the thorough answer! That's really interesting, that supplying a markdown heading into a MDX component does work.

I appreciate your time
