### ISSUE TITLE
Build fails in monorepo

### ISSUE THREAD

**Issue by Boimb** [withastro/starlight#305] opened 2023-07-05 14:55 UTC
### What version of `starlight` are you using?

0.4.1

### What version of `astro` are you using?

2.7.0

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

I'm building a project with pnpm workspaces and turbo repo.
Starlight is one of the packages of this repo.

Dev env is working seamlessly.
Build is failing tho.
I've tried the same setup in both "standalone" and "monorepo" envs, and it seems issue is related to monorepo env as "standalone" works perfectly.
Here's the error message I'm getting:
```
astro:build:  error   Cannot find module 'C:\path_to_monorepo\docs\renderers.mjs' imported from C:\path_to_monorepo\docs\astro\dist\node_modules\.pnpm\@astrojs+starlight@0.4.1_astro@2.7.0\node_modules\@astrojs\starlight\404.astro.mjs
```
Starlight root is at `C:\path_to_monorepo\docs\astro` so one level above as the requested file. Seem path related.

Thx for your support.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2023-07-05 15:02
The issue is tracked in https://github.com/withastro/astro/issues/7561.

A potential temporary workaround is to downgrade Astro to `v2.6.6`.

**Comment by Boimb** [comment] 2023-07-05 15:23
Dang. How did I miss that.
Thx for heads up.

**Comment by delucis** [comment] 2023-07-05 22:41
Thanks for the report @Boimb and sorry for the disruption. Given this isn’t something we can fix inside Starlight itself, I hope it’s OK for me to close this issue as a duplicate and hopefully we’ll get the Astro bug fixed soon. We can use https://github.com/withastro/astro/issues/7561 to track progress.

**Closed by delucis** 2023-07-05 22:41 UTC
