### ISSUE TITLE
Image not displayed in new project

### ISSUE THREAD

**Issue by druettiger** [withastro/starlight#421] opened 2023-07-27 16:14 UTC
### What version of `starlight` are you using?

0.5.6

### What version of `astro` are you using?

2.9.3

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Issue:
1. I created a new project with `npm create astro@latest -- --template starlight`.
2. The `houston.webp` image on the first page is not displayed (HTTP 404).

Possible Solution:
* Adding `experimental: { assets: true }` to `astro.config.mjs` works for me.

I am surprised that it is not included in the Starlight documentation's `docs/astro.config.mjs` though.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2023-07-27 16:58
Yes this is caused by a bug in Astro v2.9.2 and will be fixed when that PR is released in v2.9.4 — will be released when this PR is merged: https://github.com/withastro/astro/pull/7813

Thanks for helping out @HiDeoo. Will close this issue as we can't fix it on Starlight's end.

**Closed by delucis** 2023-07-27 16:58 UTC
