### ISSUE TITLE
ERROR when using <StarlightPage /> in .astro page.

### ISSUE THREAD

**Issue by sgalcheung** [withastro/starlight#2716] opened 2024-12-17 07:28 UTC
### What version of `starlight` are you using?

0.30.2

### What version of `astro` are you using?

5.0.8

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

14:51:56 [ERROR] [vite] Internal server error: No cached compile metadata found for "/Users/sgalcheung/Documents/200 - å·¥ä½œï¼ˆWorkï¼‰/220 - æŠ€èƒ½ï¼ˆSkillï¼‰/221 - CSï½œè®¡ç®—æœºç§‘å­¦ï¼ˆComputer Scienceï¼‰/221.2 - ç¼–ç¨‹è¯­è¨€å’Œç¼–è¯‘å™¨ï¼ˆProgramming language and compilerï¼‰/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/@astrojs+starlight@0.30.2_astro@5.0.8_@types+node@22.9.0_jiti@1.21.6_rollup@4.27.4_typescript@5.7.2_yaml@2.5.1_/node_modules/@astrojs/starlight/components/TableOfContents.astro?v=188ce671&astro&type=script&index=0&lang.ts". The main Astro module "/Users/sgalcheung/Documents/200 - å·¥ä½œï¼ˆWorkï¼‰/220 - æŠ€èƒ½ï¼ˆSkillï¼‰/221 - CSï½œè®¡ç®—æœºç§‘å­¦ï¼ˆComputer Scienceï¼‰/221.2 - ç¼–ç¨‹è¯­è¨€å’Œç¼–è¯‘å™¨ï¼ˆProgramming language and compilerï¼‰/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/@astrojs+starlight@0.30.2_astro@5.0.8_@types+node@22.9.0_jiti@1.21.6_rollup@4.27.4_typescript@5.7.2_yaml@2.5.1_/node_modules/@astrojs/starlight/components/TableOfContents.astro" should have compiled and filled the metadata first, before its virtual modules can be requested.
      at LoadPluginContext.load (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/220%20-%20%E6%8A%80%E8%83%BD%EF%BC%88Skill%EF%BC%89/221%20-%20CS%EF%BD%9C%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%EF%BC%88Computer%20Science%EF%BC%89/221.2%20-%20%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%92%8C%E7%BC%96%E8%AF%91%E5%99%A8%EF%BC%88Programming%20language%20and%20compiler%EF%BC%89/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/astro@5.0.8_@types+node@22.9.0_jiti@1.21.6_rollup@4.27.4_typescript@5.7.2_yaml@2.5.1/node_modules/astro/dist/vite-plugin-astro/index.js:76:15)
      at async EnvironmentPluginContainer.load (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/220%20-%20%E6%8A%80%E8%83%BD%EF%BC%88Skill%EF%BC%89/221%20-%20CS%EF%BD%9C%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%EF%BC%88Computer%20Science%EF%BC%89/221.2%20-%20%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%92%8C%E7%BC%96%E8%AF%91%E5%99%A8%EF%BC%88Programming%20language%20and%20compiler%EF%BC%89/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/vite@6.0.3_@types+node@22.9.0_jiti@1.21.6_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:46973:22)
      at async loadAndTransform (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/220%20-%20%E6%8A%80%E8%83%BD%EF%BC%88Skill%EF%BC%89/221%20-%20CS%EF%BD%9C%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%EF%BC%88Computer%20Science%EF%BC%89/221.2%20-%20%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%92%8C%E7%BC%96%E8%AF%91%E5%99%A8%EF%BC%88Programming%20language%20and%20compiler%EF%BC%89/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/vite@6.0.3_@types+node@22.9.0_jiti@1.21.6_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40786:22)
      at async viteTransformMiddleware (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/220%20-%20%E6%8A%80%E8%83%BD%EF%BC%88Skill%EF%BC%89/221%20-%20CS%EF%BD%9C%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%A7%91%E5%AD%A6%EF%BC%88Computer%20Science%EF%BC%89/221.2%20-%20%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%92%8C%E7%BC%96%E8%AF%91%E5%99%A8%EF%BC%88Programming%20language%20and%20compiler%EF%BC%89/WebFramework/Astro/starlight-squidex/node_modules/.pnpm/vite@6.0.3_@types+node@22.9.0_jiti@1.21.6_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:42296:24)

### Link to Minimal Reproducible Example

https://github.com/sgalcheung/starlight-squidex

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2024-12-17 12:49
Thank you for the issue @sgalcheung and apologies for the inconvenience. This is a duplicate of the following issues:

- https://github.com/withastro/astro/issues/12754
- https://github.com/withastro/starlight/issues/2712

I recommend subscribing to the Astro issue for updates.

**Closed by delucis** 2024-12-17 12:49 UTC
