### ISSUE TITLE
Error in StackBlitz demo

### ISSUE THREAD

**Issue by thagxt** [withastro/starlight#2730] opened 2024-12-19 18:19 UTC
### What page of the docs did you find an issue on?

Docs: https://starlight.astro.build/getting-started/
Link where error occurs: https://stackblitz.com/github/withastro/starlight/tree/main/examples/basics

### Describe the issue

When trying to run the StackBlitz demo provided in the docs, the following error is returned:

<img width="1484" alt="Screenshot 2024-12-19 at 19 18 43" src="https://github.com/user-attachments/assets/d7996c4e-0439-44cd-93d9-b83d95f7573f" />

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2024-12-20 14:54
Thanks for the report :raised_hands:

This is most likely a duplicate of https://github.com/withastro/astro/issues/12773 as we've been seeing this error intermittently in the past few days.

A workaround is to type <kbd>s</kbd> and then <kbd>enter</kbd> in the dev server terminal to force refresh content, but obviously this is only a workaround until the root cause is fixed.

**Closed by HiDeoo** 2024-12-20 14:54 UTC
