### ISSUE TITLE
Error On Favicon: unsupported file type: undefined

### ISSUE THREAD

**Issue by TheGreatAxios** [withastro/starlight#1771] opened 2024-04-19 22:13 UTC
### What version of `starlight` are you using?

0.21.5

### What version of `astro` are you using?

4.6.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Everything worked fine on Astro <3. When updating now the favicon loading breaks (or so it looks). 
I upgraded as a requirement to add Cloudflare support, but even when removing CF, the issue remains. 

`unsupported file type: undefined
  Stack trace:
    at /Users/thegreataxios/skale/docs.skale.space/node_modules/astro/dist/assets/utils/vendor/image-size/lookup.js:18:9`

### Link to Minimal Reproducible Example

https://github.com/skalenetwork/docs.skale.space/tree/thegreataxios/core/update-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment] 2024-04-20 08:02
Thanks for your report :raised_hands: I think in this case, there are 3 issues:

1. You are upgrading from `v0.11.2` to `v0.21.5` but [`v0.12.0`](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.12.0) included a breaking change to the `hero.image` frontmatter schema that you are using in your `src/content/docs/index.mdx` file.
   
   You are specifying for the `image` the following properties: `alt`, `light`, `dark` and `file`. The [schema](https://starlight.astro.build/reference/frontmatter/#hero) is now a bit more strict. It only accepts `alt` & `file` OR `alt` & `light` & `dark` OR just `html`. In your case, removing the `file` property should fix this issue.

2. In version [`0.16.0`](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.16.0), a change to an internal API (`virtual:starlight/components`) you are using was made. You will need to update your imports to use the individual virtual modules now available for each component, for example `virtual:starlight/components/EditLink`.

3. The third issue seems to be related to some of your SVGs file which encounter what seems to be this [error](https://github.com/image-size/image-size/issues/397) from the `image-size` library which is now vendored with Astro since `v4.4.0`.

Replacing the content of `src/assets/skale_logo_b.svg` and `src/assets/skale_logo_w.svg` with another SVG content seems to remove the issue and the page renders correctly.

Maybe @OliverSpeir has more ideas about this one? We may need to setup a smaller reproduction and open an issue in the Astro repository if confirmed.

**Comment by OliverSpeir** [comment] 2024-04-20 11:50
Yeah I'd say this issue can move to Astro, I was able to recreate but don't have a fix yet 


Maybe SVGO like the original image-size issue. 

I assume we can get a patch working (maybe naively underestimating the issue)

**Comment by HiDeoo** [comment] 2024-04-22 14:24
I just opened an [issue](https://github.com/withastro/astro/issues/10847) in the Astro repo regarding the SVG error with a small reproduction.

Considering the other issues where Starlight related and due to breaking changes during the upgrade process, I think we can now close this issue.

Thanks for your report (I also tagged you in the other issue so you can follow up on it).

**Closed by HiDeoo** 2024-04-22 14:24 UTC
