### ISSUE TITLE
Starlight sidebar jumps

### ISSUE THREAD

**Issue by tforward** [withastro/starlight#695] opened 2023-09-09 20:52 UTC
### What version of `starlight` are you using?

0.9.0

### What version of `astro` are you using?

3

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome (Desktop)

### Describe the Bug

If the sidebar gets long enough for content to enable the vertical scroll bar. 
Clicking an item part way down the scroll bar causes the page to jump to the top. Which can be bit jarring. 

This can be see directly in the [starlight docs page](https://starlight.astro.build/getting-started/) if force the content to enable vertical scroll.

Note: The [Astro docs](https://docs.astro.build/en/getting-started/) do not have this problem. The scroll bar functions as you'd expect and remains in place of the click.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2023-10-23 19:40
Closing as a duplicate of #307 — thanks for letting us know this is important to you!

**Closed by delucis** 2023-10-23 19:40 UTC
