### ISSUE TITLE
Full page flash using Firefox on starlight.astro.build

### ISSUE THREAD

**Issue by confiks** [withastro/starlight#2133] opened 2024-07-16 21:07 UTC
### What version of `starlight` are you using?

https://starlight.astro.build

### What version of `astro` are you using?

https://starlight.astro.build

### What package manager are you using?

https://starlight.astro.build

### What operating system are you using?

MacOS

### What browser are you using?

Firefox 128.0 and Chromium 128.0.6601.0

### Describe the Bug

When clicking on a documentation item in the sidebar, the page will do a flash to a nearly empty page before showing the clicked item. This is more apparent on slow connections, but also not really great on fast ones.

Steps to reproduce:

Using Firefox 128.0 on MacOS.

1) With a fresh browser or in private mode, go to https://starlight.astro.build/getting-started
2) Open the developer tools -> Network tab -> No Throttling -> GPRS
3) On the page, click on the documentation item "Manual setup"
4) The page flashes to nearly empty page, before showing the documentation content

On Chromium 128.0.6601.0 on MacOS, the navigation bar doesn't flash, but the content still does.

On a random (probably older deployment of) Starlight, for example https://v3.knip.dev/overview/getting-started (no affiliation; first search result), the content doesn't flash on both browsers when click a menu item. It does do a proper FOUC with big text when first loading the page, but that might be a quirk of that website (and is much more benign anyway).

### Link to Minimal Reproducible Example

https://starlight.astro.build <-- Going to astro.new immediately gives the error "Failed to get locale informations for the 'en' locale." after installing dependencies

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment] 2024-07-23 09:56
Thanks for the issue @confiks!

I was able to reproduce this in Firefox on the Starlight site:

https://github.com/user-attachments/assets/aa7edf6a-3c35-4d82-b1ee-cca98189ea69

And also confirmed that the Knip URL you shared did not behave the same way.

At the time of writing, the Knip site is using Starlight v0.24.2, so fairly up-to-date, but not 100% up-to-date (latest release is v0.25.1).

The only change since then that could plausibly impacted this might be #2025. Perhaps the script changes in that PR somehow prevent the sidebar rendering early on a very slow connection?

**Comment by delucis** [comment] 2024-07-23 11:04
Small update after doing some testing in #2141.

I think this is actually a more generic issue that is ultimately unsolvable as it’s just “how the web works”.

Each browser has some kind of logic where it will start rendering even if requests are still streaming in after some specific timeout, i.e. logic something like:

1. Request page
2. Start parsing HTML stream
3. After `n` seconds, even if HTML stream is incomplete, start rendering what it has received so far
  
(This is massively simplified probably, but this general idea.)
  
It seems like a couple of recent changes (most likely #2025) put the full sidebar HTML *just* beyond the timeout in many cases for a download speed similar to Firefox’s GPRS throttling.

In other words, this is not the fault of any specific bit of code, just a cumulative impact of everything in the first “chunk” with that connection speed and how rendering streaming HTML on a slow connection works.

This applies to everything in the nav bar essentially, so could be triggered by
- Adding lots of social links
- Having a logo SVG that is particularly complex
- Using i18n features so that Starlight adds a language picker
- etc.

And more importantly, this can be triggered by
- Slowing down the connection speed

There will always be a cut-off point where connection speed is slow enough for this behaviour to be observable. It’s how browsers work.

Now, obviously it’s still not ideal! I’ll make a note to take a look at our template to see if there is anything there that we can remove, defer, or optimize, but again, the aim there would be to reduce the _likelihood_ that a connection is slow enough for this behaviour to occur, not to eliminate the possibility.

Given this, I think I’ll close this as not technically a “bug” but still a super helpful pointer to us to stay on top of DOM size, especially in the top of the page.

Thanks again!

**Closed by delucis** 2024-07-23 11:04 UTC
